use project1;

create table Products(
	ProductID int primary key auto_increment,
    product_name varchar(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


create table Color(
	ColorId int primary key auto_increment,
    color_name varchar(255),
    color varchar(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table Rom(
	RomId int primary key auto_increment,
    rom_name varchar(255),
    romvalue int,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table Product_Detail(
ProductDetailId int primary key auto_increment,
 id_Product int ,
 screen varchar(255),
 camera_sau varchar(255),
 camera_selfie varchar(255),
 Ram varchar(255),
 DungLuongPin int,
 TheSim varchar(255),
 HĐH varchar(255),
 XuatXu varchar(255),
 Thoigianramat time,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
 );



create table Pricing(
PricingId int primary key auto_increment,
 ProductID int,
 ColorId int,
 RomId int,
 Price int,
 FOREIGN KEY (ProductID) REFERENCES Products(ProductID),
    FOREIGN KEY (ColorId) REFERENCES Color(ColorId),
    FOREIGN KEY (RomId) REFERENCES Rom(RomId)
    );
    
    
create table Images (
    ImageID INT PRIMARY KEY,
    ImageURL VARCHAR(255),
    Description TEXT,
    ProductID INT,
    ColorID int,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID),
 FOREIGN KEY (ColorID) REFERENCES Color(ColorId)
 )


    
    

-----
INSERT INTO DescriptionDetail(ProductID, Title, Image,Description) value
(1,"Khung titan cao cấp, nhẹ và bền bỉ"," ","Điểm mới đầu tiên trên iPhone 15 Pro Max mà nhà Apple nâng cấp cho sản phẩm mới của mình đó là chất liệu Titan.Thay vì thép không gỉ như các thế hệ Pro Max trước, iPhone 15 Pro Max là chiếc iPhone đầu tiên sử dụng chất liệu titan."),
(1,"Màn hình lớn, mượt và sáng"," ","Về màn hình, điểm đáng chú ý là Apple đã hoàn thiện iPhone 15 Pro Max với viền siêu mỏng kết hợp với các góc bo cong được chế tác tỉ mỉ, mang tới nét đẹp thanh lịch và sang trọng. Với việc viền màn hình mỏng hơn thì khả năng hiển thị cũng tối ưu hơn, để người dùng thao tác dễ dàng, nội dung hiển thị mãn nhãn."),
(1,"Tích hợp nút Action mới"," ","Sau rất nhiều năm, Apple đã bỏ đi thanh gạt truyền thống, thay vào đó là nút Tác Vụ (action). Đây là một phím cứng nằm ngay trên khu vực phím tăng/giảm âm lượng của iPhone 15 Pro Max. Bạn có thể gán rất nhiều tính năng cho nút Tác Vụ, như mở camera; đèn pin; ghi âm; dịch; chuyển sang chế độ im lặng/chuông, … Có thể thấy phím này rất tiện lợi khi bạn có thể tùy biến để mở nhanh tính năng mình hay sử dụng."),
(1,"Vi xử lý Apple A17 Pro mạnh mẽ đột phá"," ","Apple A17 Pro có sự nâng cấp mạnh mẽ về đồ họa, mang đến đẳng cấp mới khi chơi game di động, với độ mượt mà, sống động và chân thực của các chi tiết trong game. A17 Pro sử dụng công nghệ dò tia bằng phần cứng, nhanh gấp 4 lần dò tia bằng phần mềm để tạo hiệu ứng đồ họa và ánh sáng chân thực hơn bao giờ hết. So với thế hệ trước A16 Bionic, A17 Pro có GPU nhanh hơn 20%, tốc độ dò tia nhanh hơn 4 lần, CPU nhanh hơn 10% và Neural Engine nhanh hơn đến 2 lần."),
(1,"Camera zoom quang học 5x cực đỉnh"," ","iPhone 15 Pro Max sở hữu camera zoom quang học 5x với rất nhiều tính năng đáng chú ý. Nhờ 3 camera linh hoạt và cảm biến chất lượng, bạn có thể thay đổi góc chụp ở 7 tiêu cự khác nhau: Chụp siêu cận cảnh Macro; chụp góc siêu rộng Ultrawide; góc thông thường 1x (24mm – 28mm – 35mm); Tele 2x; Tele 5x. Nghĩa là từ chụp siêu cận, siêu rộng cho đến zoom xa, iPhone 15 Pro Max cung cấp cho người dùng rất nhiều lựa chọn chụp ảnh khác nhau."),
(1,"Sử dụng cổng USB-C, kết nối dễ dàng"," ","iPhone 15 Pro Max sử dụng cổng USB-C thay vì cổng cũ là Lightning đặc trưng. Việc chuyển đổi này giúp điện thoại dễ dàng tương thích với nhiều thiết bị và tăng cường tốc độ truyền dữ liệu."),
(2,"Chất liệu mới Titan, trải nghiệm nhẹ nhàng trên tay"," ","Một sự thay đổi lớn khi Apple đã hoàn thiện iPhone 15 Pro với khung máy titan, mang tới tổng thể nhẹ và bền bỉ hơn so với thế hệ cũ. Có thể nói, với khung titan, đây là chiếc iPhone Pro nhẹ và bền nhất của Apple từ trước đến nay."),
(2,"Màn hình viền siêu mỏng, ProMotion 120Hz mượt mà"," ","Về màn hình, điểm đáng chú ý là Apple đã hoàn thiện iPhone 15 Pro với viền siêu mỏng kết hợp với các góc bo cong được chế tác tỉ mỉ, mang tới nét đẹp thanh lịch và sang trọng. Với việc viền màn hình mỏng hơn thì khả năng hiển thị cũng tối ưu hơn, để người dùng thao tác dễ dàng, nội dung hiển thị mãn nhãn."),
(2,"Khám phá nút Tác Vụ hoàn toàn mới"," ","iPhone 15 Pro được trang bị nút Action (tác vụ) mới giống Apple Watch Ultra, để thay thế cho cần gạt rung của các đời tiền nhiệm. Theo đó, mặc định nút này sẽ có tính năng chuyển chế độ rung và im lặng. Tuy nhiên, người dùng có thể tùy chỉnh nút này cho các tính năng khác, có thể kể đến như mở camera, ứng dụng phím tắt, dịch thuật, … Điều này mang tới trải nghiệm hết sức tiện lợi khi bạn có thể sử dụng chỉ một phím cứng duy nhất để chụp hình và các tính năng khác."),
(2,"Đẳng cấp chưa từng có với Apple A17 Pro"," ","Năm nay, Apple sử dụng con chip A17 Pro cho iPhone 15 Pro. Đây là tên gọi mới so với các thế hệ chip cũ. Chip được xây dựng trên tiến trình 3nm mới, mang tới hiệu năng cực mạnh cùng khả năng tiết kiệm điện năng hiệu quả."),
(2,"Camera chụp chân dung Pro, quay video rõ nét"," ","Về camera, iPhone 15 Pro vẫn có các thông số quen thuộc như camera chính 48MP, camera tele 12MP và camera góc siêu rộng 12MP. Tuy nhiên với iPhone 15 Pro bạn sẽ có thêm nhiều tiêu cự để chụp ảnh, đồng thời khả năng chụp ảnh chân dung xóa phông được nâng cấp mạnh mẽ. Những bức ảnh sẽ có độ chi tiết và màu sắc ở một đẳng cấp mới. Điện thoại sẽ chủ động nhận diện chủ thể khi chụp ảnh và cho hiệu ứng xóa phông mà không cần phải chuyển sang chế độ Chân Dung nữa. Bên cạnh đó, iPhone 15 Pro còn có khả năng quay video Spatial, chụp ảnh 24MP và quay ProRes 4K@60fps."),
(2,"Kết nối dễ dàng với USB-C"," ","iPhone 15 Pro đều sử dụng cổng USB-C thay vì cổng cũ là Lightning đặc trưng. Việc chuyển đổi này giúp điện thoại dễ dàng tương thích với nhiều thiết bị và tăng cường tốc độ truyền dữ liệu."),
(3,"Sự khác biệt của màn hình Dynamic Island"," ","Điểm nâng cấp dễ nhận thấy nhất của iPhone 15 Plus so với thế hệ cũ là việc sản phẩm có thêm cấu trúc Dynamic Island độc đáo bên trong màn hình 6.7 inch. Với tính năng này, người dùng sẽ có được giao diện trải nghiệm mới mẻ, dễ dàng bật mở các tính năng, điều phối các hoạt động của thiết bị và duyệt thông báo nhanh."),
(3,"Làm từ chất liệu chuẩn hàng không vũ trụ"," ","Toàn bộ cấu trúc thân máy của iPhone 15 Plus được Apple chế tác và gia công cầu kỳ từ chất liệu nhôm đạt chuẩn hàng không vũ trụ. Đặc biệt, mặt lưng máy còn được trang bị thêm lớp kính chế tạo với quy trình pha màu đặc biệt, đem lại cảm nhận cực kỳ trang nhã và độc đáo. Các gam màu mà iPhone 15 Plus mang tới cho người dùng gồm có: Đen, Hồng, Vàng, Xanh lá và Xanh lam."),
(3,"Camera 48MP nâng cấp khả năng quay chụp"," ","Với việc gia tăng độ phân giải camera chính lên gấp 4 lần và đạt ngưỡng 48MP vượt trội, iPhone 15 Plus tỏ rõ thế mạnh về năng lực quay video và chụp ảnh. Mọi thước phim, mọi khuôn hình đều được thực hiện một cách chi tiết, sắc nét với màu sắc sống động tối đa."),
(3,"Trải nghiệm chụp chân dung cao cấp"," ","Lợi thế về độ phân giải và thuật toán xử lý ảnh thông minh giúp iPhone 15 Plus trở thành một trong những smartphone chụp chân dung dẫn đầu thị trường. Nét đặc trưng nhất trong cơ chế chụp chân dung của thiết bị nằm ở việc bổ sung thêm chi tiết và tái tạo màu sắc phong phú sinh động.iPhone 15 Plus sẽ tự động nhận diện khi người hoặc thú cưng xuất hiện trong khung hình để bật chế độ chụp Chân Dung và triển khai cơ chế làm mờ hậu cảnh. Đặc biệt hơn, bạn có thể nhấn trên màn hình để thay đổi chủ thể khuôn hình một cách đơn giản ngay cả với những bức hình đã chụp xong."),
(3,"Thỏa sức tận hưởng thời lượng pin dài lâu"," ","Khả năng phát video xuyên suốt 25 tiếng đồng hồ của iPhone 15 Plus khiến thiết bị trở thành model iPhone có pin dài lâu nhất. Thời lượng xem phim của thiết bị vượt trội tới 3 tiếng đồng hồ nếu so sánh với iPhone 12 trước kia."),
(3,"Hiệu năng mạnh mẽ từ bộ vi xử lý A16 Bionic"," ","A16 Bionic sẽ đảm bảo cung cấp nguồn hiệu năng tuyệt vời cho iPhone 15 Plus. Đây là bộ vi xử lý đã cho thấy được độ hiệu quả trong việc xử lý các tác vụ cao cấp. Ngoài ra, A16 Bionic cũng tạo điều kiện để iPhone 15 Plus thực hiện những tác vụ chuyên sâu hơn trong chế độ chụp chân dung và nhiếp ảnh điện toán."),
(3,"Sự tiện dụng của cổng kết nối USB-C mới"," ","Chuyển sang sử dụng cổng USB-C mới, iPhone 15 Plus đạt hiệu suất sạc pin và đồng bộ dữ liệu tốc độ cao. Bạn hoàn toàn có thể sử dụng chung một cáp kết nối cho cả iPhone, MacBook và iPad."),
(4,"Dynamic Island độc đáo, màu sắc cá tính"," ","Rất tuyệt vời, iPhone 15 đã được trang bị Dynamic Island thay thế cho thiết kế tai thỏ trước đây. Dynamic Island sẽ hiển thị linh động các cảnh báo cũng như hoạt động trực tiếp giúp bạn không bị bỏ lỡ thông tin nào. Về thiết kế, iPhone 15 sở hữu màn hình Super Retina XDR có các góc bo tròn và được làm bằng chất liệu Ceramic Shield, mặt sau làm từ kính pha màu, iPhone 15 vẫn sẽ rất nhỏ gọn với màn hình kích thước 6,1 inch."),
(4,"Camera 48MP, sắc nét đến từng chi tiết"," ","iPhone 15 sẽ được trang bị cụm camera sau có cảm biến chính 48MP hoàn toàn mới với Telephoto 2x và camera Ultra Wide 12MP, giúp bạn ghi lại mọi thứ xung quanh một cách nổi bật và chi tiết. Hơn nữa, iPhone 15 sẽ có ảnh chân dung thế hệ mới với Focus và Depth Control, sẽ tự động thu nhận thông tin về chiều sâu của bức ảnh chứa người hoặc chủ thể nào đó."),
(4,"Hiệu năng đáng kinh ngạc, thời lượng pin cả ngày"," ","Khác với 2 phiên bản iPhone 15 Pro và iPhone 15 Pro Max cao cấp hơn, iPhone 15 sử dụng con chip Apple A16 Bionic đã qua kiểm chứng với sức mạnh đáng kinh ngạc. Bộ xử lý này còn hỗ trợ cho nhiếp ảnh điện toán, cung cấp hiệu năng chơi game và làm việc mượt mà cũng như tiết kiệm năng lượng hiệu quả. Về thời lượng pin, bạn có thể xem video liên tục trong 20 giờ đồng hồ trên chiếc iPhone 15 nhỏ gọn."),
(4,"Kết nối USB-C tiên tiến"," ","iPhone 15 được kết nối và sạc với cổng USB-C thay vì cổng Lightning, có SOS cảnh báo, phát hiện va chạm và hỗ trợ công nghệ 5G. Hơn nữa, iPhone 15 sẽ sử dụng hệ điều hành iOS 17 mới nhất ngay khi xuất xưởng."),
(5,"Gặp gỡ màn hình Dynamic Island hoàn toàn mới"," ","Một sự cải tiến mang tính cách mạng của iPhone 14 Pro Max là màn hình Dynamic Island hay còn gọi màn hình “viên thuốc”. Notch được thiết kế mới, giúp camera TrueDepth nhỏ hơn 31%, tối ưu không gian. Sự cộng hưởng từ phần mềm với thuật toán chuyên biệt cho hiệu ứng sáng tạo, mang tới nhiều tính năng hữu ích. Từ đó, bạn có thể thỏa thích thực hiện những thao tác ngay trên notch như điều khiển nhạc, theo dõi tin nhắn, nhận/từ chối cuộc gọi, hiển thị thông tin, xem chỉ dẫn bản đồ, hẹn giờ… Bạn cũng có thể chạm vào Dynamic Island để chuyển nhanh tới tác vụ đang chạy. Hãy thử trải nghiệm để thấy điều khác biệt, độc quyền từ nhà Apple."),
(5,"Thiết kế bền bỉ cùng sắc màu sang trọng"," ","iPhone 14 Pro Max được hoàn thiện từ thép không gỉ cao cấp, kết hợp với kính Ceramic trứ danh, tăng cường độ bền bỉ tuyệt đối. Điện thoại cũng được bảo vệ tốt bởi chuẩn chống bụi/nước IP68, chịu được độ sâu nước tối đa 6 mét trong 30 phút. Thiết kế iPhone 14 Pro Max còn đảm bảo tính thời thượng, tinh tế với sắc màu tím Deep Purple trendy, bên cạnh các màu sang trọng Gold (vàng), Silver (bạc), Space Black (đen)."),
(5,"Chế độ Always-on Display thông minh"," ","iPhone 14 Pro Max có màn hình Always-on Display thông minh. Bạn có thể xem nhanh các thông tin cơ bản như thời gian, ngày tháng, các tiện ích, các hoạt động… mà không chạm vào điện thoại.Đặc biệt, màn hình Always-on Display trên iPhone 14 Pro Max còn có sự khác biệt khi hình nền vẫn được giữ nguyên khi kích hoạt tính năng này. Đối với những điện thoại khác, màn hình Always-on Display sẽ chuyển hoàn toàn sang màu đen. Đồng thời, nếu bạn úp mặt xuống hoặc để iPhone trong túi, điện thoại sẽ tự động tối đi, tiết kiệm pin tối ưu."),
(5,"Được trang bị màn hình Super Retina trứ danh, iPhone 14 Pro Max hiển thị chi tiết sắc nét, sống động, chuẩn từng sắc màu, cho bạn đắm chìm trong không gian giải trí riêng biệt và thư giãn hoàn toàn. Đồng thời, màn hình lớn nhất lên tới 6.7 inch, giúp thao tác thoải mái. Vượt hơn cả mong đợi, màn hình còn nhận được độ sáng tối đa lên tới 2.000nits, cho phép bạn nắm bắt mọi thông tin rõ ràng dễ dàng ngay cả ngoài trời nắng gắt. Được biết đây là độ sáng gấp đôi so với trước đây. Ngoài ra, màn hình này cũng đạt kỷ lục sáng trên thị trường smartphone."),
(5,"Công nghệ ProMotion 120Hz siêu mượt"," ","Điểm cộng cho màn hình còn là công nghệ ProMotion, đưa bạn vào trải nghiệm màn hình mượt mà. Màn hình này còn được tự động tùy chỉnh từ 10Hz đến 120Hz, giúp tiết kiệm điện năng tối ưu. Khi ứng dụng/thao tác cần tần số quét lớn, điện thoại điều chỉnh đến 120Hz. Khi không cần thiết, iPhone 14 Pro Max sẽ giảm tần số quét xuống, đảm bảo cho bạn các thao tác vừa mượt, nhanh lại không tốn quá nhiều pin."),
(5,"Camera 48MP đúng chất “Pro”"," ","Bạn sẽ không bao giờ thất vọng trên thế hệ iPhone 14 series với những cải tiến sáng giá. Đặc biệt, bản iPhone 14 Pro Max còn xứng tầm, đúng chất “Pro” với camera 48MP, cảm biến lớn 65% và độ phân giải mới gấp 4 lần so với iPhone 13 Pro Max. Đây là lần đầu tiên, thế hệ điện thoại iPhone ghi nhận độ phân giải lên tới 48MP. Những tấm ảnh được chụp bởi iPhone 14 Pro Max sẽ ghi điểm mạnh trong lòng người dùng. Apple đã sử dụng thuật toán gộp bốn pixel thành một, thu sáng nhiều hơn 4 lần và ảnh sẽ đẹp ngoạn mục so với mong đợi."),
(5,"Mọi góc ảnh trong tầm tay"," ","Bên cạnh camera 48MP, iPhone 14 Pro Max còn có camera góc rộng 12MP và camera tele 12MP cải tiến. Theo đó, camera góc siêu rộng có nhiều điểm ảnh lấy nét hơn khi có khẩu độ f/2.2. Sự kết hợp với Photonic Engine để cải thiện chất lượng ảnh. Ảnh macro cũng chụp đẹp hơn nhờ nâng cấp của camera góc rộng. Tính năng chụp macro sẽ tự động được chuyển khi phát hiện bạn đang chụp cận chủ thể."),
(5,"Chụp thiếu sáng “đỉnh cao”"," ","Vượt qua giới hạn thông thường về chụp thiếu sáng, Apple đã không ngừng nghiên cứu để mang tới cảm biến ảnh lớn, bộ xử lý hình ảnh mới thực hiện tới 4.000 tỉ thao tác trên mỗi tấm ảnh. Đồng thời, sự kết hợp của công nghệ Photonic Engine, cho phép Deep Fusion kết hợp các pixel tốt nhất từ nhiều lần phơi sáng, giữ lại các màu sắc tươi sáng, nhiều chi tiết lẫn nhiều sáng hơn, cho chất ảnh sống động, như thật."),
(5,"Quay video 4K HDR chuyên nghiệp"," ","Sử dụng chế độ quay phim độc quyền Cinematic cho phép tự động lấy nét chủ thể chuẩn xác. iPhone 14 Pro Max quay video 4K HDR ở tốc độ 24 khung hình/giây – tiêu chuẩn của ngành điện ảnh, cho những thước phim chuyên nghiệp ngay trong tay. Video còn mượt mà với tính năng chống rung mới Action Mode, bạn không cần có gimbal – mà khung hình đều sắc nét."),
(5,"Chụp ảnh selfie rạng ngời"," ","Dù chụp một mình hay chụp cùng nhóm, camera trước iPhone 14 Pro Max đều dễ dàng cho bạn tấm ảnh rạng ngời. Theo đó, camera trước TrueDepth mới với khả năng tự động lấy nét và khẩu độ lớn hơn, hiệu suất thu thập ánh sáng tốt hơn 38%, tất cả chủ thể đều rõ nét, để bạn và bạn bè đều ưng ý trong mọi lần chụp."),
(5,"Đón chào thế hệ chip siêu mạnh A16 Bionic"," ","Sức mạnh của Apple A15 Bionic hiện tại cũng đủ để chiến thắng các đối thủ. Nay thế hệ chip mới A16 Bionic còn “khủng” hơn thế nữa. A16 Bionic sản xuất trên tiến trình 4nm của TSMC, có gần 16 tỷ bóng bán dẫn, 6 lõi CPU, 5 lõi GPU cho tốc độ đầu ngành, dễ dàng xử lý mọi tác vụ “nhọc nhằn”, sẵn sàng đồng hành để máy đạt hiệu suất tối đa. Đồng thời, A16 Bionic cũng được nghiên cứu kỹ lưỡng để vừa đảm bảo hiệu năng, vừa tiết kiệm điện năng."),
(5,"Đảm bảo trải nghiệm liền mạch"," ","Không chỉ mang trong mình nhiều công nghệ đầu ngành, iPhone 14 Pro Max còn đảm bảo trải nghiệm liền mạch với viên pin lớn. Điện thoại có dung lượng pin đáng kinh ngạc. Trong một lần sạc, bạn có thể xem video đến 29 giờ. Đồng thời, sự có mặt của hỗ trợ sạc Magsafe còn cho phép bạn sạc không dây nhanh và tiện lợi hơn."),
(6,"Thanh lịch mà tươi trẻ, quen thuộc mà phá cách"," ","Ở iPhone 14 Plus, bạn sẽ tìm thấy sự cách tân từ những đường nét quen thuộc. Vẫn là bộ khung vỏ làm từ nhôm hàng không bền đẹp, camera kép đặt chéo trên mặt lưng cùng màn hình “tai thỏ” gắn liền với tên tuổi iPhone, nhưng kích cỡ màn hình giờ đây đã được kéo rộng lên ngưỡng 6.7 inch – vượt trội so với con số 6.1 inch mà iPhone 14 có được."),
(6,"Khoe dáng với các sắc thái tươi tắn"," ","Bộ sưu tập sắc màu của iPhone 14 Plus mang đến những sắc thái trẻ trung mà không kém phần lôi cuốn. Ngoài các gam trung tính như Đen, Trắng cùng sắc Đỏ sôi nổi quen thuộc, sản phẩm mang lại hai tone màu mới mẻ mà thanh lịch là Xanh dương và Tím nhạt. Tất cả đều được căn chỉnh kỹ lưỡng nhằm phát huy được nét đẹp vốn có ở iPhone 14 Plus."),
(6,"Chiếc iPhone pin tốt nhất trong lịch sử"," ","Trên trang chủ của mình, Apple tự hào giới thiệu iPhone 14 Plus là model “có thời lượng pin tốt nhất từ trước đến nay”. Với khả năng phát video không ngừng nghỉ xuyên suốt 26 giờ và hỗ trợ sạc không dây MagSafe, chiếc điện thoại tập trung phục vụ những nhu cầu thiết thực nhất của người dùng, bao gồm trải nghiệm hiển thị và thời lượng pin."),
(6,"Màn hình Super Retina XDR lớn hơn 21%"," ","Một trong những thế mạnh nổi bật nhất của iPhone 14 Plus là việc sản phẩm sở hữu màn hình lớn 6.7 inch, rộng hơn 21% so với iPhone 14 tiêu chuẩn. Tấm nền Super Retina XDR với trọng tâm là công nghệ OLED cho độ tương phản đáng kinh ngạc, mang lại những khuôn hình no màu, tươi tắn mà vẫn đảm bảo độ chân thực."),
(6,"Bước đột phá trong khả năng chụp thiếu sáng"," ","Ẩn bên trong cụm camera kép quen thuộc là những cải tiến tâm huyết của đội ngũ Apple nhằm tối ưu năng lực quay chụp cho thế hệ iPhone 2022. Camera chính của iPhone 14 Plus có thể chụp thiếu sáng tốt hơn 2.5 lần, trong khi đó, camera góc siêu rộng cũng chụp tốt hơn gấp đôi trong bối cảnh ánh sáng không thuận lợi."),
(6,"Action Mode bắt nét chuyển động cực tốt"," ","Với chế độ Action Mode, iPhone 14 Plus có khả năng bắt nét khi quay video cực tốt. Dù bạn đang đạp xe hay dạo phố, chạy bộ trong công viên hoặc muốn lưu giữ những khoảnh khắc vui đùa cùng bạn bè, iPhone 14 Plus dễ dàng đem đến những thước phim sắc nét, không nhòe mờ mặc cho bối cảnh chuyển động liên tục."),
(6,"Sẵn sàng cho video 4K chất lượng tuyệt hảo"," ","Chế độ Cinematic Mode giúp iPhone 14 Plus phát huy hết tiềm lực của cụm camera và tận dụng sức mạnh của chip xử lý để tạo nên những thước phim có độ phân giải 4K 24 FPS - tốc độ khung hình thường thấy trong chuẩn điện ảnh."),
(6,"Nâng cấp ngoạn mục ở camera TrueDepth"," ","Ở mặt trước, camera TrueDepth của iPhone 14 Plus đánh dấu sự cải tiến và nâng cấp cực kỳ mạnh mẽ so với thế hệ iPhone cũ. Với khả năng chụp thiếu sáng tốt gấp hai lần và công nghệ bắt nét tự động linh hoạt, tác vụ selfie, FaceTime và livestream trên iPhone 14 Plus sẽ không khiến bạn phải thất vọng."),
(6,"A15 Bionic bản nâng cấp: Mạnh mẽ và hiệu quả"," ","Bạn sẽ tìm thấy trên iPhone 14 Plus bộ vi xử lý A15 Bionic khác biệt so với iPhone 13. Phiên bản chip này sở hữu tới 5 lõi GPU, cho khả năng xử lý các tác vụ đồ họa, chơi game mobile và thực hiện tác vụ AR vượt trội. Không chỉ vậy, Apple còn tối ưu không gian thân máy hợp lý để giúp iPhone 14 Plus thoát nhiệt tốt, nhờ đó giúp thiết bị hoạt động lâu dài."),
(6,"Cơ chế bảo mật trứ danh nay còn tốt hơn trước"," ","Những ai từng sử dụng một chiếc iPhone chắc hẳn đều hiểu được khả năng bảo mật thông tin của dòng sản phẩm này tốt đến thế nào. Giờ đây, đội ngũ “Táo khuyết” còn nâng cấp năng lực bảo vệ dữ liệu người dùng lên một tầm cao mới nhờ tính năng Secure Enclave. A15 Bionic sẽ tạo một không gian riêng biệt để lưu trữ các thông tin cá nhân quan trọng của bạn như Face ID, danh bạ hay mật khẩu..."),
(7,"Thiết kế bền đẹp, sang trọng"," ","iPhone 14 mang trong mình khung viền phẳng được làm bởi nhôm không gỉ cao cấp, không những mang đến độ chắc chắn mà còn có sức hút bởi vẻ ngoài sang trọng. Mặt trước cũng sẽ hạn chế các va đập khi trang bị kính cường lực Ceramic Shield có độ bền tốt nhất hiện nay. Tất cả trên iPhone 14 đều giữ được nét đặc trưng, tương đồng với những gì mà Apple đã làm trong 3 năm qua. "),
(7,"Tùy chỉnh và trải nghiệm thú vị với iOS 16"," ","iPhone 14 với iOS 16 sẽ cho phép bạn tùy chỉnh Màn hình khóa của mình theo những cách mới đầy thú vị, điều mà iPhone chưa thể làm trong thời gian vừa qua. Bức ảnh màn hình khóa của bạn sẽ thêm phần nổi bật và lung linh. Các thông báo cũng được điều chỉnh trông gọn gàng hơn hay những tính năng trên iMessage… tất cả đang chờ bạn trải nghiệm. "),
(7,"Hệ thống cảnh báo khẩn cấp mới"," ","Với iPhone 14 series, dù bạn không có kết nối Wi-Fi hay mạng di động để phát cảnh báo nếu chẳng may gặp trục trặc, bạn vẫn có thể phát cảnh báo SOS khẩn cấp qua vệ tinh để kịp thời ứng cứu. iPhone 14 còn có thể phát hiện một vụ tai nạn ô tô nghiêm trọng và thông báo cho các liên hệ khẩn cấp của bạn."),
(7,"Màn hình sắc nét, trải nghiệm tuyệt đỉnh"," ","iPhone 14 tiếp tục sử dụng ngôn ngữ thiết kế đặc trưng với thiết kế notch tai thỏ đã làm nên tên tuổi. Điện thoại sử dụng công nghệ màn hình OLED mang lại độ tương phản cao lên đến 2.000.000:1, cung cấp khả năng hiển thị cực sắc nét. Hơn nữa, màn hình này còn cung cấp độ chính xác của màu sắc cao, đạt chuẩn HDR, có TrueTone và độ sáng tối đa có thể đạt đến 1200 nits. Khá đáng tiếc là iPhone 14 không hỗ trợ Always-on Display và Dynamic Island."),
(7,"Camera rực sáng dù ngày hay đêm"," ","Camera chính trên iPhone 14 được cải tiến so với thế hệ trước và khả năng xử lý hình ảnh cũng được nâng lên tầm cao mới, cho phép bạn ghi lại nhiều bức ảnh sống động và sắc nét dù ở bất kỳ môi trường sáng nào. Khả năng chụp thiếu sáng trên iPhone 14 thực sự ấn tượng khi camera chính chụp tốt hơn 2.5 lần, camera Ultra Wide chụp tốt hơn 2 lần so với iPhone 13. Dù ngày hay đêm, những bức ảnh được cho ra từ điện thoại sẽ luôn rực sáng, đầy đủ chi tiết và màu sắc luôn sống động."),
(7,"Chụp đêm đầy màu sắc ngay trên camera selfie"," ","Những bức ảnh chụp nhóm hay cận cảnh “tự sướng” trên iPhone 14 luôn sắc nét và đầy màu sắc với camera TrueDepth mới có khả năng tự động lấy nét và khẩu độ lớn hơn. Khả năng thu sáng trên camera này tốt hơn 38%, cung cấp nhiều chi tiết hơn và ít nhiễu hơn cho video và ảnh tự chụp của bạn. "),
(7,"Video luôn mượt mà với Action Mode"," ","Với iPhone 14 và Action Mode trong tay, những thước phim hành động của bạn giờ đây không phải là vấn đề lớn. Dù đang vận động với các bài tập chạy bộ hay tập thể dục, điện thoại vẫn ghi lại một video mượt mà, xác định chính xác chủ thể đang chuyển động mà không cần sử dụng Gimbal. "),
(7,"Quay video chất lượng chuẩn điện ảnh"," ","Với chế độ điện ảnh trên iPhone 14, nó sẽ tự động chuyển tiêu điểm đến chủ thể quan trọng và tập trung vào đó. Thước phim mà điện thoại cung cấp sẽ đạt chuẩn điện ảnh về chất lượng cũng như khả năng xử lý với chất lượng 4K ở tốc độ 24fps. iPhone 14 xứng đáng là chiếc smartphone có video chất lượng cao hàng đầu hiện nay. "),
(7,"Thời lượng pin được cải thiện đáng kể, dùng cả ngày"," ","iPhone 14 được cung cấp một thời lượng pin tuyệt vời khi có thể duy trì cả ngày cho một lần sạc nhờ vào những cải tiến và tối ưu tốt bằng thuật toán phần mềm. Những trải nghiệm của bạn trên thiết bị sẽ luôn diễn ra liền mạch và hơn hết là khả năng nạp đầy năng lượng nhanh chóng. "),
(7,"Hiệu suất mạnh mẽ với Apple A15 Bionic "," ","iPhone 14 sử dụng bộ xử lý siêu cấp có trên iPhone 13 Pro là Apple A15 Bionic để cung cấp hiệu năng. Bộ xử lý này tích hợp GPU lên đến 5 lõi mang đến sức mạnh toàn diện cho mọi tính năng mới nhất và những tựa game đồ họa cao sẽ được đáp ứng một cách đáng kinh ngạc. iPhone 14 sẽ có hiệu quả tản nhiệt cao hơn thế hệ trước nhờ vào sự tối ưu trong thiết kế lại linh kiện bên trong, bạn có thể sử dụng máy lâu hơn mong đợi mà không lo bị nóng."),
(8,"Thanh lịch, cao cấp mà quen thuộc"," ","iPhone 13 có kiểu dáng chuẩn phong cách Apple với thân máy nhôm bền nhẹ kết hợp cùng hai mặt kính, sử dụng màn hình “tai thỏ” gắn liền với thương hiệu iPhone trong nhiều năm. Cầm chiếc điện thoại lên, bạn sẽ cảm nhận được độ hoàn thiện cao và chất lượng hàng đầu thế giới."),
(8,"Tôn vinh thiết kế đẳng cấp bằng các sắc màu trẻ"," ","Vẻ bóng bẩy của iPhone 13 tiêu chuẩn được Apple tôn vinh bằng các lựa chọn màu đa phong cách. Những ai yêu vẻ đẹp trung tính có thể tìm tới màu Trắng và Đen; người năng động sẽ phù hợp với sắc Đỏ, Xanh; màu Hồng dành cho các bạn nữ nhẹ nhàng đằm thắm; còn lựa chọn Xanh lá thuộc về những khách hàng tìm kiếm sự trầm ổn mà bí ẩn."),
(8,"Cụm camera kép giản đơn mà hiệu quả"," ","Không cần đến sự hỗ trợ của quá nhiều ống kính, hệ thống camera iPhone 13 vẫn phô diễn khả năng quay chụp hàng đầu với sự kết hợp của hai camera 12MP đặt chéo trên mặt lưng theo góc 45 độ. Cách sắp xếp khéo léo của “Táo khuyết” giúp module camera có đủ không gian chứa kích thước cảm biến lớn, khẩu độ rộng mở và cả phần cứng chống rung quang học. So với thế hệ iPhone 12 trước đây, sản phẩm cho thấy năng lực thu sáng tốt hơn 47%, khả dụng với cả tác vụ chụp ảnh và quay phim."),
(8,"Chế độ điện ảnh Cinematic thỏa sức sáng tạo"," ","Những lợi thế mà công nghệ Cinematic đem lại giúp iPhone 13 tạo điều kiện cho các ý tưởng sáng tạo mạnh mẽ. Bạn sẽ hóa thân thành nhà quay phim chuyên nghiệp khi vận dụng những chức năng của Cinematic như xóa phông video, chuyển chủ thể bắt nét trong khung hình cực mượt."),
(8,"Luôn chụp đủ sáng, dù ngày hay đêm"," ","Về chất lượng camera, iPhone 13 không đòi hỏi thực hiện tác vụ phức tạp nào, chỉ cần đưa máy lên và chụp, thiết bị sẽ trả về khuôn hình chất lượng khiến bạn ưng ý. Những cải tiến cả trong phần cứng, phần mềm đem lại chế độ làm mờ hậu cảnh hết sức nghệ thuật."),
(8,"Mở rộng tầm nhìn qua camera siêu rộng"," ","iPhone 13 được trang bị camera góc siêu rộng, giúp bạn bắt trọn góc nhìn toàn cảnh trước mắt. Không cần di chuyển thiết bị, bạn vẫn dễ dàng lưu lại vẻ đẹp bao la của cảnh sắc trong những chuyến du lịch trải nghiệm. Để làm được điều này, Apple đã tích hợp cho iPhone 13 cảm biến ảnh chất lượng hơn trong camera Ultra Wide để chụp tốt hơn trong bối cảnh ánh sáng không lý tưởng."),
(8,"Sử dụng hệ thống camera trước cao cấp"," ","Giống như các camera đặt phía sau, camera trước trên iPhone 13 có độ phân giải tương đương là 12MP. Ngoài tác vụ selfie thông thường, chủ nhân chiếc điện thoại cũng có thể thực hiện các tính năng nâng cao và hấp dẫn như chụp đêm, Smart HDR 4, chụp xóa phông hoặc quay video bằng công nghệ Cinematic. Hệ thống camera TrueDepth sẽ phụ trách quét để nhận diện khuôn mặt người dùng, tăng thêm độ bảo mật an toàn, bảo vệ cho mọi thông tin quan trọng của bạn."),
(8,"Màn hình sáng hơn 28%, tấm nền Super Retina XDR"," ","Sự quyến rũ trên màn hình iPhone 13 có được là nhờ tấm nền Super Retina XDR hiện đại, với trọng tâm là công nghệ OLED hàng đầu thế giới smartphone. Không gian hiển thị của sản phẩm sẽ tái tạo những khung hình mượt mà sắc sảo, diễn đạt màu sắc chân thật, tự nhiên."),
(8,"Trải nghiệm pin nhiều hơn 2.5 giờ"," ","Những cải tiến về dung lượng kèm theo việc chip A15 Bionic vận hành rất tiết kiệm điện giúp iPhone 13 có thể vận hành hiệu quả mà không hao hụt năng lượng nhiều. Apple cho biết iPhone 13 có thể kéo dài thời lượng tổng thể thêm 2.5 giờ, giảm bớt nỗi bận tâm tìm kiếm sạc pin của người dùng."),
(8,"Sức mạnh bất ngờ của chip A15 Bionic"," ","Trọng tâm công nghệ của iPhone 13 nằm ở bộ vi xử lý A15 Bionic với CPU mạnh hơn 50% và GPU vượt trội 30% khi đặt cạnh thế hệ chip cũ. Sự hiện diện của con chip trong thân máy giúp sản phẩm xử lý mọi tác vụ chỉ trong tích tắc, bao gồm cả những chế độ phức tạp như Cinematic hay chơi game nặng."),
(8,"Công cụ để bạn bước vào kỷ nguyên 5G"," ","Bước chuyển đổi mạnh mẽ từ hạ tầng 4G sang 5G hứa hẹn sẽ giúp tốc độ truyền tải dữ liệu trở nên nhanh chóng hơn nhiều so với hiện tại. iPhone 13 sẽ giúp bạn đón đầu xu thế này khi chip A15 Bionic được thiết kế để hỗ trợ chuẩn mạng di động thế hệ thứ năm. Bạn có thể dễ dàng tải các video nặng, xem phim chất lượng 4K và chơi game online với tốc độ cực kỳ xuất sắc."),
(9,"Thiết kế thanh lịch, cứng cáp và đẳng cấp"," ","So với iPhone 11, phiên bản iPhone 12 sở hữu kiểu dáng thanh lịch và thân thiện hơn với cấu trúc thân máy được làm mỏng thêm 11%, rút gọn tiết diện tổng thể thêm 15% và giảm trọng lượng 16%. Chiếc điện thoại bạn đang theo dõi sở hữu màn hình 6.1 inch mà vẫn đảm bảo tính gọn nhẹ cơ động. Bộ khung vỏ nhôm được vát phẳng các cạnh tạo nên ngôn ngữ thiết kế thanh lịch, quyến rũ."),
(9,"Bảo vệ mặt trước với lớp phủ Ceramic Shield"," ","Sự cao cấp của iPhone 12 được thể hiện ngay từ cách Apple lựa chọn vật liệu hoàn thiện thiết bị. Cụ thể, hãng sử dụng một lớp gốm Ceramic Shield cứng cáp phủ lên toàn bộ mặt trước iPhone 12, gia tăng độ chịu lực và năng lực chống xước. Toàn bộ cấu trúc viền được bo gọn tối đa để đem lại cảm giác thanh thoát, trọn vẹn khi nhìn ngắm, quan sát."),
(9,"Bảo vệ mặt trước với lớp phủ Ceramic Shield"," ","Sự cao cấp của iPhone 12 được thể hiện ngay từ cách Apple lựa chọn vật liệu hoàn thiện thiết bị. Cụ thể, hãng sử dụng một lớp gốm Ceramic Shield cứng cáp phủ lên toàn bộ mặt trước iPhone 12, gia tăng độ chịu lực và năng lực chống xước. Toàn bộ cấu trúc viền được bo gọn tối đa để đem lại cảm giác thanh thoát, trọn vẹn khi nhìn ngắm, quan sát."),
(9,"Đa sắc thái với nhiều lựa chọn màu"," ","Các lựa chọn màu tác động mạnh đến phong cách của iPhone 12, sản phẩm đem đến bộ sưu tập gồm sáu màu sắc gồm: Tím, Xanh dương, Xanh lá, Đỏ, Trắng và Đen. Hãy thoải mái thể hiện cá tính riêng của bạn qua việc tìm tới phiên bản dành cho mình."),
(9,"Chào mừng bạn đến với kỷ nguyên kết nối 5G"," ","iPhone 12 được trang bị công nghệ mạng 5G với tốc độ rất cao, nhờ vậy, sản phẩm sẽ hỗ trợ các tác vụ xem video, chơi game và gọi FaceTime sắc nét cực kỳ nhanh chóng. Trong bối cảnh thế hệ mạng di động thứ 5 ngày càng vươn lên thay thế 4G, việc sở hữu iPhone 12 sẽ giúp bạn được tận hưởng công nghệ tương tác nhanh chưa từng có."),
(9,"Được trang bị chip A14 Bionic mạnh mẽ hàng đầu"," ","Apple đã ưu ái trang bị cho iPhone 12 bộ vi xử lý A14 Bionic có tốc độ vượt trội, đây là con chip mạnh mẽ đầu bảng và là chip xử lý đầu tiên trên toàn cầu được chế tác trên tiến trình 5nm, bao gồm 11,8 tỷ bóng bán dẫn, 6 nhân CPU và 4 nhân GPU. Sự góp mặt của A14 Bionic giúp iPhone 12 có thể xử lý các tác vụ nặng mà vẫn tiết kiệm pin. Nhà Táo đã tăng số lõi Neural Engine từ 8 lên 16 để giúp chip dễ dàng học hỏi thói quen từ trải nghiệm của người dùng."),
(9,"Công nghệ Super Retina XDR rực rỡ và chi tiết"," ","Không gian hiển thị của iPhone 12 đánh dấu sự nâng cấp mạnh mẽ so với iPhone 11. Không chỉ có viền màn hình rút gọn, chất lượng những khuôn hình cũng được cải thiện hơn nhiều nhờ tấm nền OLED cực độ sắc sảo, đem tới các hình ảnh sắc nét, chi tiết, đạt độ tương phản 2.000.000:1, diễn đạt màu sắc phong phú và thể hiện sắc đen sâu. Bạn sẽ ấn tượng trước những gì mà iPhone 12 thể hiện."),
(9,"Camera không ngại màn đêm"," ","Công nghệ chụp đêm Night mode được Apple đưa lên cả camera góc rộng và camera góc siêu rộng, từ đó tối ưu năng lực chụp sáng xuất sắc. Riêng camera chính 12MP của iPhone 12 đạt mức khẩu độ lớn F/1.6, giúp gia tăng năng lực thu sáng thêm 27%. Dù bạn thực hiện khuôn hình trong bối cảnh ban ngày hay ban đêm thì các yếu tố như độ chi tiết và màu sắc cũng hiện lên một tác phẩm nghệ thuật thực thụ."),
(9,"Khả năng chụp ấn tượng của Smart HDR 3"," ","iPhone 12 được trang bị tính năng Smart HDR 3, cho phép chụp xuất sắc trong mọi bối cảnh, từ những khung hình với điều kiện ánh sáng phức tạp cho đến góc chụp không thuận sáng. Apple đã khéo léo sử dụng công nghệ trí tuệ nhân tạo (AI) để gia tăng năng lực nhận diện cảnh sắc và cân bằng trắng, để chất lượng ảnh chụp thành phẩm trở nên tốt hơn."),
(9,"Thể hiện năng lực chụp đêm cực ấn tượng"," ","Apple đã đưa công nghệ chụp đêm Night Mode đồng thời lên camera sau và cả camera trước trên iPhone 12. Nhờ vậy, mỗi khuôn hình selfie của bạn đều rực rỡ và đầy tính nghệ thuật bất chấp bối cảnh xung quanh. Các chức năng selfie khác của iPhone 12 bao gồm Deep Fusion, Smart HDR 3, quay video 4K HDR Dolby Vision."),
(10,"Bộ màu sắc cá tính và thời trang"," ","iPhone 11 đem đến bộ màu sắc cá tính và hết sức trẻ trung, bao gồm Đen, Trắng, Đỏ, Tím, Vàng, Xanh lục. Mỗi màu sắc đều được Apple tuyển chọn kỹ càng sao cho hợp nhất với thiết kế tổng thể của sản phẩm. Thiết bị sở hữu bộ khung vỏ chế tác từ chất liệu nhôm nguyên khối liền mạch, phô diễn vẻ đẹp thanh lịch, cao cấp mà vẫn trẻ trung."),
(10,"Lưu trữ mọi khoảnh khắc với camera kép"," ","Bên trong cụm camera kép của iPhone 11, bạn sẽ tìm thấy một camera chính góc rộng và một camera hỗ trợ góc siêu rộng, cả hai đều có độ phân giải 12MP cho năng lực bắt nét tự động gấp 3 lần bất chấp bối cảnh ánh sáng không lý tưởng. Sự hỗ trợ từ camera góc siêu rộng giúp mở rộng góc chụp tới 4 lần và cực kỳ hữu ích để lưu lại các khuôn hình phong cảnh rộng mở trong các chuyến du lịch."),
(10,"Trải nghiệm quay phim chuyên nghiệp thực thụ"," ","Sự kết hợp của hệ thống camera 12MP + 12MP giúp iPhone 11 có thể sáng tạo nên những thước phim cực độ ấn tượng với chất lượng 4K 60fps sắc sảo. iPhone 11 sẽ dễ dàng bắt trọn mọi chuyển động để tạo nên các video mượt mà trọn vẹn. Đặc biệt, sản phẩm được hỗ trợ công nghệ thu âm tập trung vào một chủ thể nào đó qua thao tác thu – phóng hình ảnh, thiết bị sẽ tự động tập trung thu âm ở chính chủ thể bạn zoom."),
(10,"Chụp ảnh thiếu sáng xuất sắc cùng Night Mode"," ","Những thách thức về ánh sáng không thể cản bước iPhone 11. Nhờ sự hỗ trợ của chế độ chụp đêm Night Mode, hệ thống ống kính của iPhone 11 có thể thu sáng cực tốt dù điều kiện ngoại cảnh không thực sự lý tưởng. Chẳng cần đến sự hỗ trợ của đèn flash, mỗi bức ảnh bạn thực hiện từ sản phẩm này đều cho thấy vẻ sống động, nét tự nhiên và màu sắc hài hòa."),
(10,"Xóa phông xuất sắc, làm mờ tuyệt hảo"," ","Cầm iPhone 11 trên tay, bạn sẽ có được công cụ chụp ảnh chân dung tuyệt hảo nhờ cơ chế xóa phông làm mờ hậu cảnh. Đưa máy lên và chụp, hình ảnh của bạn cùng người bạn thân sẽ hiện lên rõ ràng sắc nét, bức hình sẽ trở nên có chiều sâu hơn với hiệu ứng ánh sáng Studio. Bạn sẽ bất ngờ trước khả năng phân biệt chủ thể và hậu cảnh chính xác của iPhone 11."),
(10,"Xử lý ảnh xuất sắc dù ánh sáng phức tạp"," ","Ứng dụng công nghệ AI và Máy Học, camera iPhone 11 phô diễn khả năng vận hành thông minh thông qua tính năng Smart HDR. Nhờ vậy, chiếc điện thoại sẽ tự động nhận diện chủ thể khuôn hình để áp dụng các tinh chỉnh đặc biệt. Bạn sẽ thấy những khuôn mặt hiện diện trong bức ảnh có độ chi tiết cao và tông màu da cực kỳ tự nhiên, phần phông nền phía sau được diễn đạt ấn tượng theo một cách khác. Nhờ Smart HDR, iPhone 11 có thể xử lý các khuôn hình xuất sắc, bất chấp bối cảnh ánh sáng phức tạp."),
(10,"Camera selfie 12MP với chất lượng vượt trội"," ","Đến thế hệ iPhone 11, Apple đã cải tiến để nâng cấp camera selfie lên mức 12MP, đem tới các khuôn hình sắc sảo và chất lượng. Ngoài ra, nhà Táo còn tích hợp thêm chức năng slofie để hỗ trợ quay các video slowmotion 120 fps được thực hiện bởi chính camera trước. Hãy lưu lại những giây phút thú vị trong cuộc sống theo cách của bạn."),
(10,"Cấu trúc bền bỉ, ngâm nước 2 mét trong 30 phút"," ","iPhone 11 sử dụng cấu trúc thân vỏ vững vàng với chất liệu kính cường lực cực bền. Ngoài ra, việc đạt chuẩn chống nước, chống bụi IP68 cũng giúp sản phẩm vận hành ổn định ở mực nước sâu 2 mét trong nửa tiếng, bạn không cần lo lắng đến những sự cố về nước có thể bất chợt xảy ra trong quá trình sử dụng."),
(10,"Liquid Retina sống động và chân thực"," ","Về khả năng hiển thị hình ảnh, iPhone 11 được trang bị màn hình 6.1 inch Liquid Retina giúp tối ưu những khuôn hình hiển thị theo cách ấn tượng nhất. Khả năng cân bằng trắng tuyệt hảo sẽ tự động căn chỉnh dựa trên ánh sáng từ môi trường, thể hiện nhiệt độ màu cực kỳ dễ chịu. Ngoài ra, tính năng Haptic Touch cũng giúp việc phản hồi xúc giác trên iPhone 11 trở nên linh hoạt hơn."),
(10,"Thời lượng dài lâu, thoải mái trải nghiệm"," ","Nhờ Apple tối ưu tốt giữa phần cứng và phần mềm, iPhone 11 cho thấy thời lượng sử dụng dài lâu xuyên suốt cả ngày. Bạn sẽ thoải mái chơi game, xem phim, nghe nhạc và lướt web mà không cần bận tâm quá nhiều về pin. Khi cạn năng lượng, thiết bị sẽ tái tạo nhanh chóng qua cơ chế sạc nhanh, chỉ cần nửa tiếng là có được 50% pin, thoải mái sử dụng."),
(10,"A13 Bionic mạnh mẽ đến khó tin"," ","iPhone 11 được trang bị một trong những con chip mạnh mất từ trước đến nay là A13 Bionic. Nhờ vậy, sản phẩm thể hiện sức mạnh khác biệt để đảm bảo mọi thứ được vận hành nhanh chóng, mượt mà. Hãy thỏa sức đắm mình vào những tựa game đòi hỏi cao về cấu hình trên iPhone 11. Cầm chiếc điện thoại trong tay, bạn sẽ có tự tin rằng sản phẩm sẽ phục vụ mình tốt trong nhiều năm tới."),
(10,"Cải tiến Face ID: Tiện lợi hơn, bảo mật hơn"," ","Face ID mới được cải tiến cho phép bạn mở khóa iPhone 11 64GB nhanh chóng và dễ dàng hơn bao giờ hết. Thậm chí Face ID còn tiện lợi và bảo mật hơn cả phương án truyền thống là cảm biến vân tay Touch ID. Bạn có thể dùng tính năng này để đăng nhập vào ứng dụng, tài khoản, ngân hàng và thanh toán với Apple Pay. Tất cả thông tin đều được bảo mật tuyệt đối khi Face ID không hề lưu trữ hay chia sẻ hình ảnh của bạn. Kể cả khi gửi ảnh hay gọi FaceTime, hình ảnh của bạn cũng được mã hóa an toàn.")
